---
collections:
  - name: community.docker
    version: ">=3.0.0"
  - name: ansible.posix
    version: ">=1.4.0"

roles:
  - name: geerlingguy.docker
    version: "7.0.2"
  - name: geerlingguy.pip
    version: "2.2.0"