# Group Variables for Development Environment
---
# Environment Configuration
environment: development
project_name: myproject
domain_name: "example.com"

# Docker Configuration
docker_version: "24.0"
docker_compose_version: "v2.21.0"

# Application Configuration
backend_image: "YOUR_DOCKERHUB_ORG/myproject-backend-dev:latest"
frontend_image: "YOUR_DOCKERHUB_ORG/myproject-frontend-dev:latest"

# Replica Configuration
frontend_replicas: 2
backend_replicas: 2

# Database Configuration
postgres_db: "{{ vault_postgres_db | default('myproject_dev') }}"
postgres_user: "{{ vault_postgres_user | default('myproject') }}"
postgres_password: "{{ vault_postgres_password }}"
postgres_replica_user: "{{ vault_postgres_replica_user | default('replicator') }}"
postgres_replica_password: "{{ vault_postgres_replica_password }}"

# PgBouncer Configuration
pgbouncer_pool_mode: session
pgbouncer_pool_size: 20
pgbouncer_max_client_conn: 100

# PgAdmin Configuration (optional)
pgadmin_email: "{{ vault_pgadmin_email | default('admin@example.dev') }}"
pgadmin_password: "{{ vault_pgadmin_password }}"

# Traefik Configuration
traefik_log_level: INFO
traefik_api_dashboard: true
acme_email: "{{ vault_acme_email }}"
traefik_auth_users: "{{ vault_traefik_auth_users }}"


# JWT Configuration
jwt_secret: "{{ vault_jwt_secret }}"
jwt_expires_in: "1h"

# Stack Environment Variables
stack_environment:
  # Domain Configuration
  DOMAIN_NAME: "{{ domain_name }}"
  
  # Application
  ENVIRONMENT: "{{ environment }}"
  BACKEND_IMAGE: "{{ backend_image }}"
  FRONTEND_IMAGE: "{{ frontend_image }}"
  BACKEND_REPLICAS: "{{ backend_replicas }}"
  FRONTEND_REPLICAS: "{{ frontend_replicas }}"
  
  # Database
  POSTGRES_DB: "{{ postgres_db }}"
  POSTGRES_USER: "{{ postgres_user }}"
  POSTGRES_PASSWORD: "{{ postgres_password }}"
  POSTGRES_REPLICA_USER: "{{ postgres_replica_user }}"
  POSTGRES_REPLICA_PASSWORD: "{{ postgres_replica_password }}"
  
  # PgBouncer
  PGBOUNCER_POOL_MODE: "{{ pgbouncer_pool_mode }}"
  PGBOUNCER_POOL_SIZE: "{{ pgbouncer_pool_size }}"
  PGBOUNCER_MAX_CLIENT_CONN: "{{ pgbouncer_max_client_conn }}"
  
  # PgAdmin
  PGADMIN_EMAIL: "{{ pgadmin_email }}"
  PGADMIN_PASSWORD: "{{ pgadmin_password }}"
  
  # Traefik
  TRAEFIK_LOG_LEVEL: "{{ traefik_log_level }}"
  TRAEFIK_API_DASHBOARD: "{{ traefik_api_dashboard }}"
  ACME_EMAIL: "{{ acme_email }}"
  TRAEFIK_AUTH_USERS: "{{ traefik_auth_users }}"
  
  # JWT
  JWT_SECRET: "{{ jwt_secret }}"
  JWT_EXPIRES_IN: "{{ jwt_expires_in }}"

# Monitoring Configuration
monitoring_enabled: true
prometheus_retention: "15d"
grafana_admin_password: "{{ vault_grafana_admin_password }}"

# Backup Configuration
backup_enabled: true
backup_retention_days: 7
backup_s3_bucket: "myproject-dev-backups"

# Security Configuration
ssl_enabled: true
cors_origins: 
  - "https://{{ domain_name }}"
  - "https://traefik.{{ domain_name }}"