# Configuração Principal do Sistema de Segurança Pro-Mata
# Arquivo: security/security-config.yml

system:
  name: "Pro-Mata Security System"
  version: "1.0.0"
  environment: "dev"  # dev|staging|prod
  
monitoring:
  enabled: true
  interval: 30  # segundos
  log_level: "INFO"  # DEBUG|INFO|WARN|ERROR
  retention_days: 30
  
  alerts:
    discord_webhook: ""
    email_notifications: false
    slack_integration: false
    
    thresholds:
      critical: 1
      high: 5
      medium: 10

scanning:
  enabled: true
  schedule: "0 2 * * *"  # Diário às 2h
  types:
    - "containers"
    - "images"
    - "dependencies"
    - "network"
    - "infrastructure"
  
  retention:
    reports: 90  # dias
    scan_data: 30  # dias

secrets:
  rotation:
    enabled: true
    schedule:
      database: 30  # dias
      api_keys: 90  # dias
      jwt: 7  # dias
      ssl: 365  # dias
  
  backup:
    enabled: true
    retention: 5  # backups
    encryption: true

compliance:
  enabled: true
  standards:
    - "OWASP"
    - "CIS"
  
  checks:
    - "password_policy"
    - "ssl_configuration" 
    - "firewall_rules"
    - "file_permissions"
    - "user_access"

reporting:
  enabled: true
  formats:
    - "html"
    - "json"
    - "pdf"
  
  schedule: "0 6 * * 1"  # Segunda-feira às 6h
  recipients:
    - "security@promata.com.br"

dashboard:
  enabled: true
  port: 8080
  auth_required: false  # Para desenvolvimento
  auto_refresh: 30  # segundos
