# Pro-Mata Stack Deployment Playbook
---
- name: Deploy Pro-Mata Stack
  hosts: managers
  become: true
  gather_facts: true
  
  vars_files:
    - "../inventory/{{ env | default('dev') }}/group_vars/all.yml"
  
  tasks:
    - name: Create Pro-Mata directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
      loop:
        - /opt/promata/stacks
        - /opt/promata/configs
        - /opt/promata/configs/prometheus
        - /opt/promata/logs
        - /opt/promata/data

    - name: Create Docker networks
      docker_network:
        name: "{{ item }}"
        driver: overlay
        scope: swarm
        attachable: true
      loop:
        - promata_public
        - promata_internal
        - promata_database

    - name: Copy stack file based on environment
      copy:
        src: "../../docker/stacks/{{ stack_file | default('dev-complete.yml') }}"
        dest: "/opt/promata/stacks/{{ stack_file | default('dev-complete.yml') }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'

    - name: Copy Prometheus configuration
      copy:
        src: "../../docker/configs/prometheus/prometheus.yml"
        dest: "/opt/promata/configs/prometheus/prometheus.yml"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'

    - name: Generate dev environment file
      template:
        src: "templates/dev.env.j2"
        dest: /opt/promata/.env
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'

    - name: Deploy Pro-Mata stack
      shell: |
        cd /opt/promata
        export $(cat .env | grep -v '^#' | grep -v '^$' | xargs)
        docker stack deploy -c stacks/{{ stack_file | default('dev-complete.yml') }} promata-{{ env | default('dev') }} --with-registry-auth
      register: stack_deploy_result
      
    - name: Display stack deployment result
      debug:
        var: stack_deploy_result.stdout_lines
      
    - name: Wait for stack services to initialize
      pause:
        seconds: 45
        prompt: "Waiting for Pro-Mata services to initialize..."

    - name: Verify stack deployment
      command: docker service ls --filter "label=com.docker.stack.namespace=promata-{{ env | default('dev') }}"
      register: stack_services
      
    - name: Display deployed services
      debug:
        var: stack_services.stdout_lines

    - name: Check critical services health
      command: docker service ps promata-{{ env | default('dev') }}_{{ item }} --no-trunc
      register: service_status
      loop:
        - traefik
        - postgres  
        - pgadmin
        - grafana
      ignore_errors: yes

    - name: Display critical service health
      debug:
        msg: "{{ item.item }} service status: {{ item.stdout_lines }}"
      loop: "{{ service_status.results }}"
      when: item.stdout_lines is defined

    - name: Test service connectivity
      uri:
        url: "https://{{ item }}.{{ domain_name }}"
        method: GET
        validate_certs: no
        timeout: 10
      register: service_connectivity
      loop:
        - grafana
        - pgadmin
      ignore_errors: yes

    - name: Display connectivity test results
      debug:
        msg: "Service {{ item.item }}: {{ 'ACCESSIBLE' if item.status == 200 or item.status == 308 else 'NOT ACCESSIBLE (' + item.status|string + ')' }}"
      loop: "{{ service_connectivity.results }}"
      when: item.status is defined

    - name: Display deployment summary
      debug:
        msg:
          - "🚀 Pro-Mata dev environment deployment completed!"
          - "🌐 Frontend: https://{{ domain_name }}"
          - "🔧 API: https://api.{{ domain_name }}"
          - "📊 Grafana: https://grafana.{{ domain_name }}"
          - "🗄️  PgAdmin: https://pgadmin.{{ domain_name }}"
          - "📊 Traefik: https://traefik.{{ domain_name }}"
          - "🔐 Simple passwords: admin/admin, promata/password123"