# Ansible Inventory for Pro-Mata Development Environment
---
all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: "/home/frequency-overloader/Documents/infrastructure/ssh-keys/dev-ssh-key"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    env: dev

  children:
    promata_dev:
      children:
        managers:
          hosts:
            swarm-manager:
              ansible_host: "{{ manager_public_ip }}"
              private_ip: "{{ manager_private_ip }}"
              node_role: manager

        workers:
          hosts:
            swarm-worker:
              ansible_host: "{{ worker_public_ip }}"
              private_ip: "{{ worker_private_ip }}"
              node_role: worker
              ansible_ssh_common_args: '-o StrictHostKeyChecking=no'