# Generated from envs/dev/.env
# Mon 01 Sep 2025 07:46:59 AM -03

environment = "dev  "
env_color = "blue                          # Para UI diferenciada"
env_prefix = "dev"
domain_name = "promata.com.br"
subdomain_prefix = "dev                    # dev.promata.com.br"
api_subdomain = "api-dev                   # api-dev.promata.com.br  "
admin_subdomain = "admin-dev               # admin-dev.promata.com.br"
azure_resource_group = "pro-mata-dev-rg"
azure_subscription_id = "PLACEHOLDER_REPLACE_WITH_YOUR_SUBSCRIPTION_ID"
azure_location = "eastus2"
vm_size = "Standard_B2s                    # Menor para dev"
backend_image = "norohim/pro-mata-backend-dev:latest"
frontend_image = "norohim/pro-mata-frontend-dev:latest"
replicas = "1                              # Apenas 1 réplica para dev"
postgres_db = "promata_dev"
database_size = "Basic                     # Menor para dev"
monitoring_enabled = "true"
prometheus_retention = "7d                 # Menor retenção"
cloudflare_api_token = "your_api_token_here"
