# Variables for Azure Development Environment

variable "resource_group_name" {
  description = "The name of the resource group"
  type        = string
  default     = "rg-myproject-dev"
}

variable "location" {
  description = "The Azure region where resources will be created"
  type        = string
  default     = "East US 2"
}

variable "environment" {
  description = "Environment name"
  type        = string
  default     = "dev"
}

variable "project_name" {
  description = "Project name"
  type        = string
  default     = "myproject"
}

variable "vm_size" {
  description = "Size of the Azure VM (equivalent to AWS t2.medium)"
  type        = string
  default     = "Standard_B2ms"
}

# SSH keys are now auto-generated by Terraform

variable "storage_account_name" {
  description = "Name of the storage account (must be globally unique)"
  type        = string
  default     = "myprojectdevstore"

  validation {
    condition     = can(regex("^[a-z0-9]{3,24}$", var.storage_account_name))
    error_message = "Storage account name must be between 3 and 24 characters, lowercase letters and numbers only."
  }
}

variable "docker_compose_version" {
  description = "Docker Compose version to install"
  type        = string
  default     = "2.21.0"
}

variable "common_tags" {
  description = "Common tags for all resources"
  type        = map(string)
  default = {
    Project     = "myproject"
    Environment = "dev"
    ManagedBy   = "terraform"
    Owner       = "myproject-team"
  }
}

# Database configuration
variable "postgres_db" {
  description = "PostgreSQL database name"
  type        = string
  default     = "myproject_dev"
}

variable "postgres_user" {
  description = "PostgreSQL username"
  type        = string
  default     = "myproject"
}

# Application configuration
variable "domain_name" {
  description = "Domain name for the application"
  type        = string
  default     = "dev.example.com"
}

variable "backend_image" {
  description = "Backend Docker image"
  type        = string
  default     = "YOUR_DOCKERHUB_ORG/myproject-backend-dev:latest"
}

variable "frontend_image" {
  description = "Frontend Docker image"
  type        = string
  default     = "YOUR_DOCKERHUB_ORG/myproject-frontend-dev:latest"
}

variable "backend_replicas" {
  description = "Number of backend service replicas"
  type        = number
  default     = 2
}

variable "frontend_replicas" {
  description = "Number of frontend service replicas"
  type        = number
  default     = 2
}

# Cloudflare variables
variable "cloudflare_api_token" {
  description = "Cloudflare API Token with Zone:Read, DNS:Edit permissions"
  type        = string
  sensitive   = true
  default     = null
}

variable "cloudflare_zone_id" {
  description = "Cloudflare Zone ID for your domain"
  type        = string
  default     = null
}

variable "enable_cloudflare_dns" {
  description = "Enable Cloudflare DNS management"
  type        = bool
  default     = true
}

variable "azure_location" {
  description = "Azure location (alias for location)"
  type        = string
  default     = "eastus2"
}

variable "monitoring_enabled" {
  description = "Enable monitoring and logging"
  type        = bool
  default     = true
}

variable "migration_image" {
  description = "Migration Docker image"
  type        = string
  default     = "YOUR_DOCKERHUB_ORG/myproject-migration-dev:latest"
}