name: Deploy Dev Environment (Alternative Auth)

on:
  repository_dispatch:
    types: [deploy-dev-frontend, deploy-dev-backend]
  workflow_dispatch:
    inputs:
      force_deploy:
        description: 'Force full deployment'
        required: false
        default: 'false'

env:
  ENV: dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Tools
        run: |
          # Install Terraform
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install -y terraform ansible make

      # Alternative: Use Azure CLI with subscription ID only (limited functionality)
      - name: Azure CLI Setup (Subscription Only)
        run: |
          # Install Azure CLI
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          
          # Note: This requires manual login or device code authentication
          # For CI/CD, you'll need to set up proper service principal credentials
          echo "⚠️  Azure authentication setup required"
          echo "Please run: ./scripts/setup/azure-service-principal-setup.sh"

      - name: Create Environment File
        run: |
          cat > envs/${{ env.ENV }}/.env.${{ env.ENV }} << EOF
          # Azure Configuration (Limited - needs service principal)
          AZURE_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_RESOURCE_GROUP=promata-dev-rg
          AZURE_LOCATION=eastus2
          
          # Domain Configuration
          DOMAIN_NAME=dev.promata.com.br
          
          # Infrastructure
          TF_VAR_ssh_public_key="${{ secrets.SSH_PUBLIC_KEY }}"
          EOF

      - name: Validate Configuration
        run: |
          echo "🔍 Validating infrastructure configuration..."
          make terraform-validate ENV=${{ env.ENV }}
          
      - name: Show Setup Instructions
        run: |
          echo "🚨 Azure Authentication Required"
          echo "================================"
          echo ""
          echo "Your Azure Student account needs service principal setup."
          echo "Please run the following steps:"
          echo ""
          echo "1. Install Azure CLI locally:"
          echo "   curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash"
          echo ""
          echo "2. Run the setup script:"
          echo "   ./scripts/setup/azure-service-principal-setup.sh"
          echo ""
          echo "3. Add the generated secrets to GitHub:"
          echo "   https://github.com/AGES-Pro-Mata/infrastructure/settings/secrets/actions"
          echo ""
          echo "Required secrets:"
          echo "- AZURE_CREDENTIALS"
          echo "- AZURE_CLIENT_ID"
          echo "- AZURE_CLIENT_SECRET" 
          echo "- AZURE_TENANT_ID"
          echo "- AZURE_SUBSCRIPTION_ID (✅ already set)"
