name: Docker Hub Webhook Handler

# NOTA: Este workflow recebe webhooks diretos do Docker Hub quando novas imagens são publicadas
# Alternativamente, os repos backend/frontend podem usar repository_dispatch após push para Docker Hub
# Se usando repository_dispatch nos repos de aplicação, este workflow pode ser desabilitado

on:
  # GitHub webhook endpoint que o Docker Hub irá chamar diretamente
  # Configurar em: Docker Hub → Repository → Webhooks → Add webhook
  # URL: https://api.github.com/repos/AGES-Pro-Mata/infrastructure/dispatches
  # Content Type: application/json
  # Payload: {"event_type": "docker-hub-webhook", "client_payload": {...}}
  repository_dispatch:
    types: [docker-hub-webhook]

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}

jobs:
  process-webhook:
    runs-on: ubuntu-latest
    outputs:
      should_deploy: ${{ steps.webhook.outputs.should_deploy }}
      image_type: ${{ steps.webhook.outputs.image_type }}
      image_tag: ${{ steps.webhook.outputs.image_tag }}
      repository_name: ${{ steps.webhook.outputs.repository_name }}
    
    steps:
      - name: Process Docker Hub Webhook
        id: webhook
        run: |
          echo "🐳 Processing Docker Hub webhook..."
          
          # Extract webhook payload data
          REPO_NAME="${{ github.event.client_payload.repository.repo_name }}"
          PUSHED_TAG="${{ github.event.client_payload.push_data.tag }}"
          PUSHER="${{ github.event.client_payload.push_data.pusher }}"
          
          echo "Repository: $REPO_NAME"
          echo "Tag: $PUSHED_TAG"
          echo "Pusher: $PUSHER"
          
          # Check if this is a development image with 'latest' tag
          if [[ "$REPO_NAME" == "norohim/pro-mata-backend-dev" ]] && [[ "$PUSHED_TAG" == "latest" ]]; then
            echo "✅ Backend dev image with latest tag detected"
            echo "should_deploy=true" >> $GITHUB_OUTPUT
            echo "image_type=backend" >> $GITHUB_OUTPUT
            echo "image_tag=latest" >> $GITHUB_OUTPUT
            echo "repository_name=$REPO_NAME" >> $GITHUB_OUTPUT
          elif [[ "$REPO_NAME" == "norohim/pro-mata-frontend-dev" ]] && [[ "$PUSHED_TAG" == "latest" ]]; then
            echo "✅ Frontend dev image with latest tag detected"
            echo "should_deploy=true" >> $GITHUB_OUTPUT
            echo "image_type=frontend" >> $GITHUB_OUTPUT
            echo "image_tag=latest" >> $GITHUB_OUTPUT
            echo "repository_name=$REPO_NAME" >> $GITHUB_OUTPUT
          elif [[ "$REPO_NAME" == "norohim/pro-mata-database-dev" ]] && [[ "$PUSHED_TAG" == "latest" ]]; then
            echo "✅ Database dev image with latest tag detected"
            echo "should_deploy=true" >> $GITHUB_OUTPUT
            echo "image_type=database" >> $GITHUB_OUTPUT
            echo "image_tag=latest" >> $GITHUB_OUTPUT
            echo "repository_name=$REPO_NAME" >> $GITHUB_OUTPUT
          elif [[ "$REPO_NAME" == "norohim/pro-mata-migration-dev" ]] && [[ "$PUSHED_TAG" == "latest" ]]; then
            echo "✅ Migration dev image with latest tag detected"
            echo "should_deploy=true" >> $GITHUB_OUTPUT
            echo "image_type=migration" >> $GITHUB_OUTPUT
            echo "image_tag=latest" >> $GITHUB_OUTPUT
            echo "repository_name=$REPO_NAME" >> $GITHUB_OUTPUT
          else
            echo "ℹ️ Image doesn't match dev deployment criteria"
            echo "should_deploy=false" >> $GITHUB_OUTPUT
          fi

      - name: Log Webhook Details
        run: |
          echo "## 🐳 Docker Hub Webhook Received" >> $GITHUB_STEP_SUMMARY
          echo "- **Repository**: ${{ steps.webhook.outputs.repository_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Tag**: ${{ steps.webhook.outputs.image_tag }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Image Type**: ${{ steps.webhook.outputs.image_type }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Should Deploy**: ${{ steps.webhook.outputs.should_deploy }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Timestamp**: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY

  trigger-deployment:
    needs: process-webhook
    if: needs.process-webhook.outputs.should_deploy == 'true'
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger Unified Deployment (Enhanced)
        run: |
          echo "🚀 Triggering unified deployment with IP preservation..."
          
          # Simple approach - always use latest tags and let deploy-unified handle it
          BACKEND_IMAGE="norohim/pro-mata-backend-dev:latest"
          FRONTEND_IMAGE="norohim/pro-mata-frontend-dev:latest"
          
          echo "Backend image: $BACKEND_IMAGE"
          echo "Frontend image: $FRONTEND_IMAGE"
          echo "Updated component: ${{ needs.process-webhook.outputs.image_type }}"
          
          # Dispatch to unified deployment workflow
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/dispatches" \
            -d '{
              "event_type": "docker-hub-auto-deploy",
              "client_payload": {
                "environment": "dev",
                "backend_image": "'$BACKEND_IMAGE'",
                "frontend_image": "'$FRONTEND_IMAGE'",
                "trigger_source": "docker_hub_webhook",
                "updated_component": "${{ needs.process-webhook.outputs.image_type }}",
                "repository_name": "${{ needs.process-webhook.outputs.repository_name }}",
                "timestamp": "'$(date -u '+%Y-%m-%d %H:%M:%S UTC')'"
              }
            }'

      - name: Notify Discord - Auto Deployment Started
        run: |
          echo "📢 Sending Discord notification..."
          
          WEBHOOK_URL="${{ secrets.DISCORD_WEBHOOK_URL }}"
          if [[ -n "$WEBHOOK_URL" ]]; then
            curl -X POST "$WEBHOOK_URL" \
              -H "Content-Type: application/json" \
              -d '{
                "embeds": [{
                  "title": "🤖 Auto-Deployment Triggered",
                  "description": "Docker Hub webhook detected new `latest` tag",
                  "color": 3447003,
                  "fields": [
                    {
                      "name": "📦 Updated Image",
                      "value": "`${{ needs.process-webhook.outputs.repository_name }}`",
                      "inline": true
                    },
                    {
                      "name": "🏷️ Tag",
                      "value": "`${{ needs.process-webhook.outputs.image_tag }}`",
                      "inline": true
                    },
                    {
                      "name": "🌍 Environment",
                      "value": "`dev`",
                      "inline": true
                    },
                    {
                      "name": "⚡ Trigger",
                      "value": "Automatic via Docker Hub webhook",
                      "inline": false
                    }
                  ],
                  "timestamp": "'$(date -u '+%Y-%m-%dT%H:%M:%S.000Z')'"
                }]
              }' || echo "Failed to send Discord notification"
          else
            echo "Discord webhook URL not configured"
          fi

  notify-ignored:
    needs: process-webhook
    if: needs.process-webhook.outputs.should_deploy == 'false'
    runs-on: ubuntu-latest
    
    steps:
      - name: Log Ignored Webhook
        run: |
          echo "ℹ️ Docker Hub webhook received but ignored"
          echo "Repository: ${{ github.event.client_payload.repository.repo_name }}"
          echo "Tag: ${{ github.event.client_payload.push_data.tag }}"
          echo "Reason: Not a dev image with 'latest' tag"
          
          echo "## ℹ️ Webhook Ignored" >> $GITHUB_STEP_SUMMARY
          echo "Docker Hub webhook was received but ignored because it doesn't match our deployment criteria:" >> $GITHUB_STEP_SUMMARY
          echo "- Repository: \`${{ github.event.client_payload.repository.repo_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Tag: \`${{ github.event.client_payload.push_data.tag }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Criteria**: Only \`norohim/pro-mata-*-dev:latest\` images trigger auto-deployment" >> $GITHUB_STEP_SUMMARY
