name: Notify Discord on PR opened

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

env:
  DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL_PR }}

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Post to Discord
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          REPO: ${{ github.repository }}
        run: |
          payload=$(jq -n \
            --arg repo "$REPO" \
            --arg title "$PR_TITLE" \
            --arg url "$PR_URL" \
            --arg author "$PR_AUTHOR" \
            '{
              content: "<@&1399565960922402929><@&1399580242636701726> **\($repo)**",
              embeds: [
                {
                  title: $title,
                  url: $url,
                  description: "Autor: \($author)"
                }
              ]
            }')
          curl -sS -X POST -H "Content-Type: application/json" -d "$payload" "$DISCORD_WEBHOOK_URL"