name: Quick Tests

on:
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install -y terraform ansible make

      - name: Run Tests
        run: |
          make terraform-validate ENV=dev
          make ansible-validate ENV=dev